### ISSUE TITLE
Better unfocus refocus managment 

### ISSUE THREAD

**Issue by DamTobor** [TeamRobotmad/BadgeBot#22]
For example, the `PatternEnable`/`PatternDisable` events are not always correct. If you minimise and return to app the LEDs are competed for by pattern because there is no new disable event.

**Comment by DamTobor** [comment]
This was attempted using the app focus pop push events, but the LEDs still flicker.

**Comment by Robotmad** [comment]
sorted in PR#53

**Comment by Robotmad** [comment]
PR#53
