### ISSUE TITLE
Use .mpy as more efficient format for released app(s)

### ISSUE THREAD

**Issue by DamTobor** [TeamRobotmad/BadgeBot#24]
Would require workflow for prepping repo for release, by producing `.mpy` files and removing uneeded files

For debugging, copying code for app loading might have to deal with app being `.py` or `.mpy`

**Comment by Robotmad** [comment]
as we've already exceeded the size of .py app which the EEPROM can hold we can't use .py any more for debugging - at least until we do a special build of HexDrive hexpansions with larger EEPROMs.
